### ISSUE TITLE
本地套接字超时是“00:04:59.9910000”

### ISSUE THREAD

**Issue by xuleihuanying** [hzexe/openair#2]
获取所有数据时，显示：
异常:已捕获: "套接字连接已中止。这可能是由于处理消息时出错或远程主机超过接收超时或者潜在的网络资源问题导致的。本地套接字超时是“00:04:59.9910000”。" (System.ServiceModel.CommunicationException)

**Comment by hzexe** [comment]
抱歉现在才更新
这种问题看是网络连接超时，但很可能是网址已变化了，把库文件更新到最新版本可解决
