### ISSUE TITLE
能不能写一个example:如何获取北京，杭州的某段时间的小时PM2.5的数据！

### ISSUE THREAD

**Issue by J08056** [hzexe/openair#4]
你 好，能不能提供一个example:如何获取北京，杭州的某段时间的小时PM2.5的数据！

**Comment by hzexe** [comment]
example里有类似的示例:
https://github.com/hzexe/openair/blob/044e27ed7ae990814127c6025f5bbe427d398829/example/Program.cs#L92
注释掉的那行加城市过滤条件就成。

或是获取这个城市所有检测站在某时的数据，再算这个城市的平均值,参考这块示例
https://github.com/hzexe/openair/blob/044e27ed7ae990814127c6025f5bbe427d398829/example/Program.cs#L113
